/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "usart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int programState = OFF;

int main(void)
{
	gpioInit();
	usart2Init();
    /* Superloop */
	for(;;) {
		writeUSART2('T');
		writeUSART2('e');
		writeUSART2('s');
		writeUSART2('t');
		writeUSART2('\n');
		// ledToggle();
		// setProgramState(&programState);
		// displayProgramState(&programState);
	}
}
